[[redirects]]
  from = "/ges-archive.html"
  to = "/ges-archive.html"
  status = 200

[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200

[[redirects]]
  from = "/certificate.png"
  to = "/certificate.png"
  status = 200

[[redirects]]
  from = "/certificate.svg"
  to = "/certificate.svg"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
